Update CreateSchemaQuery.java
When you try to execute the 2 VerdictDB.sql commands back to back :
getting the runtime error:
org.verdictdb.exception.VerdictDBDbmsException: Issued the following query: create schema verdictdbtemp
org.apache.hadoop.hive.metastore.api.AlreadyExistsException: Database verdictdbtemp already exists;

    at org.verdictdb.connection.SparkConnection.executeSingle(SparkConnection.java:166)
    at org.verdictdb.connection.SparkConnection.execute(SparkConnection.java:148)
at org.verdictdb.connection.CachedDbmsConnection.execute(CachedDbmsConnection.java:49)
    at org.verdictdb.connection.DbmsConnection.execute(DbmsConnection.java:41)
    at org.verdictdb.coordinator.SelectQueryCoordinator.process(SelectQueryCoordinator.java:128)
    
This is because: createSchema does not use `IF NOT EXISTS` hence causing the error. 

Fixed this problem in CreateSchemaQuery() constructor